name: HiDrive Next Build

# SPDX-FileCopyrightText: 2023 Nextcloud GmbH and Nextcloud contributors
# SPDX-FileCopyrightText: 2024 STRATO AG
# SPDX-License-Identifier: AGPL-3.0-or-later

# The HiDrive Next source is packaged as a container image.
# This is a workaround because releases can not be created without tags
# and we want to be able to create snapshots from branches.

on:
  pull_request:
    paths:
      - '.github/workflows/**'
      - 'src/**'
      - 'custom-npms/**'
      - 'apps/**'
      - 'apps/**/appinfo/info.xml'
      - 'apps-custom/**'
      - 'apps-external/**'
      - 'IONOS'
      - 'package.json'
      - 'package-lock.json'
      - 'themes/**'
      - 'tsconfig.json'
      - '**.js'
      - '**.ts'
      - '**.vue'
  push:
    branches:
      - main
      - master
      - stable*
      - ionos-dev
      - ionos-dev30

env:
  TARGET_PACKAGE_NAME: hidrive-next.zip
  TARGET_ARCHIVE_NAME: hidrive-next.tar.gz
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  # set this to folder name in the repository e.g. <my_test_folder/>
  # in order to be able the to test the workflow in "own" folder
  ARTIFACTORY_DEBUG_PREFIX: "mk_ignore"
  ARTIFACTORY_REPOSITORY_SNAPSHOT: ionos-productivity-hdnext-snapshot

permissions:
  contents: read

jobs:
  hidrive-next-build:
    runs-on: self-hosted

    permissions:
      contents: read
      packages: write

    outputs:
      NC_VERSION: ${{ steps.get_nc_version.outputs.NC_VERSION }}

    name: hidrive-next-build
    steps:
      - name: Checkout server
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7
        with:
          submodules: true

      - name: Set up node with version from package.json's engines
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version-file: "package.json"

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y make zip unzip

      - name: Print dependencies versions
        run: make --version && node --version && npm --version

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@c541c155eee45413f5b09a52248675b1a2575231 #v2.31.1
        with:
          tools: composer:v2
          extensions: gd, zip, curl, xml, xmlrpc, mbstring, sqlite, xdebug, pgsql, intl, imagick, gmp, apcu, bcmath, redis, soap, imap, opcache
        env:
          runner: self-hosted

      - name: Print PHP install
        run: php -i && php -m

      - name: Build Nextcloud
        run: make -f IONOS/Makefile build_nextcloud FONTAWESOME_PACKAGE_TOKEN=${{ secrets.FONTAWESOME_PACKAGE_TOKEN }}

      - name: Install dependencies & build simplesettings app
        env:
          CYPRESS_INSTALL_BINARY: 0
          PUPPETEER_SKIP_DOWNLOAD: true
        run: make -f IONOS/Makefile build_dep_simplesettings_app

      - name: Install dependencies & build viewer app
        env:
          CYPRESS_INSTALL_BINARY: 0
          PUPPETEER_SKIP_DOWNLOAD: true
        run: make -f IONOS/Makefile build_dep_viewer_app

      - name: Install dependencies & build user_oidc app
        env:
          CYPRESS_INSTALL_BINARY: 0
          PUPPETEER_SKIP_DOWNLOAD: true
        run: make -f IONOS/Makefile build_dep_user_oidc_app

      - name: Install dependencies for external apps nc_ionos_processes
        run: make -f IONOS/Makefile build_dep_nc_ionos_processes_app

      - name: Build Custom CSS
        run: make -f IONOS/Makefile build_dep_theming_app

      - name: Install dependencies & build IONOS theme custom elements
        env:
          CYPRESS_INSTALL_BINARY: 0
          PUPPETEER_SKIP_DOWNLOAD: true
        run: make -f IONOS/Makefile build_dep_ionos_theme

      - name: Add config partials
        run: make -f IONOS/Makefile add_config_partials

      - name: Zip dependencies
        run: make -f IONOS/Makefile zip_dependencies TARGET_PACKAGE_NAME=${{ env.TARGET_PACKAGE_NAME }}

      - name: Archive build artifact
        run: make -f IONOS/Makefile archive_artifact TARGET_PACKAGE_NAME=${{ env.TARGET_ARCHIVE_NAME }}

      - name: Get NC version
        id: get_nc_version
        run: |
          NC_VERSION=$(jq -r '.ncVersion' version.json)
          echo "NC_VERSION=$NC_VERSION" >> $GITHUB_OUTPUT

      - name: Upload artifact result for job hidrive-next-build
        uses: actions/upload-artifact@v4
        with:
          retention-days: 30
          name: hidrive_next_build_artifact
          path: |
            ${{ env.TARGET_PACKAGE_NAME }}
            ${{ env.TARGET_ARCHIVE_NAME }}

      - name: Show changes on failure
        if: failure()
        run: |
          git status
          git --no-pager diff
          exit 1 # make it red to grab attention

  upload-to-artifactory:
    runs-on: self-hosted

    permissions:
      contents: read
      packages: write

    name: Push artifact to artifactory
    needs: hidrive-next-build

    steps:
      - name: Download artifact zip
        uses: actions/download-artifact@v4
        with:
          name: hidrive_next_build_artifact

      # This action sets up the JFrog CLI with the Artifactory URL and access token
      - uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.JF_ARTIFACTORY_URL }}
          JF_USER: ${{ secrets.JF_ARTIFACTORY_USER }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

      - name: Ping the JF server
        run: |
          # Ping the server
          jf rt ping
          # Collect environment variables for the build
          #jf rt bce
          # Collect VCS details from git and add them to the build
          #jf rt bag
          # Publish build info
          #jf rt bp

      - name: Upload PR build to artifactory
        if: github.event_name == 'pull_request'
        id: artifactory_upload
        run: |
          export BUILD_NAME="hidrive_next-snapshot"
          export BUILD_NUMBER="${{ github.run_number }}"

          # differentiate between "ionos-dev", "pr-<number>", "branch/<branch-name>"
          export BUILD_SOURCE="branch/${{ github.ref_name }}"

          # check if in pull request
          if [ -n "${{ github.event.pull_request.head.repo.full_name }}" ]; then
              export BUILD_SOURCE="pr-${{ github.event.pull_request.number }}"
          else
            # check if current branch is ionos-dev
            if [ "${{ github.ref_name }}" == "ionos-dev" ]; then
                export BUILD_SOURCE="dev"
            fi
          fi

          export PACKAGE_BUILD_NAME="${{ env.ARTIFACTORY_DEBUG_PREFIX }}/${BUILD_SOURCE}"

          export PATH_TO_DIRECTORY="${{ env.ARTIFACTORY_REPOSITORY_SNAPSHOT }}/${PACKAGE_BUILD_NAME}"
          export PATH_TO_DIRECTORY_BUILD="${PATH_TO_DIRECTORY}/build-${BUILD_NUMBER}/"
          export PATH_TO_DIRECTORY_W_VERSION="${PATH_TO_DIRECTORY}/hidrive-next-${{ needs.hidrive-next-build.outputs.NC_VERSION }}.tar.gz"

          # Upload the build to Artifactory as build
          echo jf rt upload "${{ env.TARGET_ARCHIVE_NAME }}" \
          --build-name $BUILD_NAME \
          --build-number $BUILD_NUMBER \
          $PATH_TO_DIRECTORY_BUILD

          # Promote current build to the "latest" build
          echo jf rt upload "${{ env.TARGET_ARCHIVE_NAME }}" \
          --build-name $BUILD_NAME \
          --build-number $BUILD_NUMBER \
          $PATH_TO_DIRECTORY_W_VERSION

      - name: Collect Build Info
        if: false
        run: |
          export BUILD_NAME="hidrive_next-snapshot"
          export BUILD_NUMBER="${{ github.run_number }}"

          jf rt build-collect-env $BUILD_NAME $BUILD_NUMBER

      - name: Publish Build Info
        if: false
        run: |
          export BUILD_NAME="hidrive_next-snapshot"
          export BUILD_NUMBER="${{ github.run_number }}"

          jf rt build-publish $BUILD_NAME $BUILD_NUMBER

      - name: Show changes on failure
        if: failure()
        run: |
          git status
          git --no-pager diff
          exit 1 # make it red to grab attention

  hidirve-next-artifact-to-ghcr_io:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    name: Push artifact to ghcr.io
    needs: hidrive-next-build

    steps:
      - name: Download artifact zip
        uses: actions/download-artifact@v4
        with:
          name: hidrive_next_build_artifact

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"

      - name: Create Dockerfile
        run: |
          cat >Dockerfile << EOF
          FROM busybox as builder
          COPY ./${{ env.TARGET_PACKAGE_NAME }} /
          WORKDIR /builder
          RUN unzip /${{ env.TARGET_PACKAGE_NAME }} -d /builder

          FROM scratch
          WORKDIR /app
          VOLUME /app
          COPY --from=builder /builder /app
          EOF

      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Show changes on failure
        if: failure()
        run: |
          exit 1 # make it red to grab attention
